"""added Condition

Revision ID: 349848e5818b
Revises: d2a5140368fd
Create Date: 2023-06-30 21:59:23.764043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349848e5818b'
down_revision = 'd2a5140368fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='level'), nullable=False),
    sa.Column('type', sa.Enum('tense', 'word', 'irreg_verb', name='type'), nullable=False),
    sa.Column('text', sa.String(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condition')
    # ### end Alembic commands ###
