"""add unique question field

Revision ID: d2a5140368fd
Revises: a1f867263c1e
Create Date: 2023-06-30 18:57:23.047486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a5140368fd'
down_revision = 'a1f867263c1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exwriting', schema=None) as batch_op:
        batch_op.create_unique_constraint('exwriting', ['question'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exwriting', schema=None) as batch_op:
        batch_op.drop_constraint('exwriting', type_='unique')

    # ### end Alembic commands ###
